<a href="https://colab.research.google.com/github/Aryannchoudhary/Machine_learning_Models/blob/main/LSTM%26GNU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('qoute_dataset.csv')

In [ ]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
df['quote'][0]

'“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”'

In [ ]:
df.shape

(3038, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3038 entries, 0 to 3037
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   quote   3038 non-null   object
 1   Author  3038 non-null   object
dtypes: object(2)
memory usage: 47.6+ KB

In [ ]:
df.isnull().sum()

quote     0
Author    0
dtype: int64

In [ ]:
quotes=df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [ ]:
quotes=quotes.str.lower()

In [ ]:
import string
translator=str.maketrans('','',string.punctuation)
quotes=quotes.apply(lambda x:x.translate(translator))

In [ ]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
vocab_size=8978
tokenizer=Tokenizer(num_words=vocab_size)
tokenizer.fit_on_texts(quotes)

In [ ]:

word_index=tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [ ]:
sequence=tokenizer.texts_to_sequences(quotes)

In [ ]:
for i in range(3):
  print(quotes[i])

“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”
“it is our choices harry that show what we truly are far more than our abilities”
“there are only two ways to live your life one is as though nothing is a miracle the other is as though everything is a miracle”

In [ ]:
for i in range(3):
  print(sequence[i])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]
[947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]
[1337, 14, 53, 201, 714, 3, 81, 15, 36, 37, 7, 29, 329, 93, 7, 5, 1157, 1, 101, 7, 29, 329, 126, 7, 5, 3677]

In [ ]:
X=[]
y=[]


for seq in sequence:
  for i in range(1,len(seq)):
    input_seq=seq[:i]
    output_seq=seq[i]
    X.append(input_seq)
    y.append(output_seq)

In [ ]:
len(X)

85270

In [ ]:
len(y)

85270

In [ ]:
max_len=max(len(x)for x in X)
print(max_len)

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded=pad_sequences(X, maxlen=max_len, padding='pre')

In [ ]:
X_padded[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0, 713], dtype=int32)

In [ ]:
y=np.array(y)

In [ ]:
y.shape

(85270,)

In [ ]:
X_padded.shape

(85270, 745)

In [ ]:
# one hot encoding on y
from tensorflow.keras.utils import to_categorical
y_one_hot=to_categorical(y, num_classes=vocab_size)

In [ ]:
y_one_hot.shape

(85270, 8978)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN,LSTM, Dense

In [ ]:
embed_dim=50
rnn_units=128

RNN

In [ ]:
rnn_model=Sequential()

In [ ]:
rnn_model.add(
    Embedding(input_dim=vocab_size, output_dim=embed_dim, input_length=max_len)
)
rnn_model.add(
    SimpleRNN(rnn_units, return_sequences=True)
)
rnn_model.add(
    SimpleRNN(rnn_units)
)
rnn_model.add(
    Dense(vocab_size, activation='softmax')
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [ ]:
rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [ ]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_1 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

LSTM

In [ ]:
lstm_model=Sequential()
lstm_model.add(
    Embedding(input_dim=vocab_size, output_dim=embed_dim,
              input_length=max_len)
)
lstm_model.add(
    LSTM(rnn_units)
)

lstm_model.add(
    Dense(units=vocab_size, activation='softmax')
)

In [ ]:
lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy'])

In [ ]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
epochs=10
batch_size=128

In [ ]:
history_rnn=rnn_model.fit(
    X_padded, y_one_hot,
    epochs=epochs,
    batch_size=batch_size,
    validation_split=0.2
)

Epoch 1/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 81s 140ms/step - accuracy: 0.0401 - loss: 6.7484 - val_accuracy: 0.0460 - val_loss: 6.6605
Epoch 2/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 68s 127ms/step - accuracy: 0.0619 - loss: 6.2461 - val_accuracy: 0.0684 - val_loss: 6.5966
Epoch 3/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 70s 132ms/step - accuracy: 0.0760 - loss: 6.0271 - val_accuracy: 0.0766 - val_loss: 6.4517
Epoch 4/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 78s 125ms/step - accuracy: 0.0936 - loss: 5.7298 - val_accuracy: 0.0863 - val_loss: 6.4316
Epoch 5/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 69s 130ms/step - accuracy: 0.1074 - loss: 5.4705 - val_accuracy: 0.0960 - val_loss: 6.4700
Epoch 6/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 67s 126ms/step - accuracy: 0.1206 - loss: 5.2299 - val_accuracy: 0.0963 - val_loss: 6.5064
Epoch 7/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 71s 133ms/step - accuracy: 0.1329 - loss: 5.0102 - val_accuracy: 0.0970 - val_loss: 6.5613
Epoch 8/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 66s 123ms/step - accuracy: 0.1465 - loss: 4.8064 - val_accuracy: 0.0984 - val_loss: 6.6654
Epoch 9/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 66s 124ms/step - accuracy: 0.1605 - loss: 4.6132 - val_accuracy: 0.0989 - val_loss: 6.6992
Epoch 10/10
533/533 ━━━━━━━━━━━━━━━━━━━━ 66s 125ms/step - accuracy: 0.1783 - loss: 4.4330 - val_accuracy: 0.0989 - val_loss: 6.7948

In [ ]:
history_lstm=lstm_model.fit(
    X_padded, y_one_hot,
    epochs=100,
    batch_size=batch_size,
    validation_split=0.2
)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 57ms/step - accuracy: 0.0389 - loss: 6.7430 - val_accuracy: 0.0420 - val_loss: 6.7391
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.0546 - loss: 6.3316 - val_accuracy: 0.0589 - val_loss: 6.6454
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.0741 - loss: 6.0845 - val_accuracy: 0.0815 - val_loss: 6.5286
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.0918 - loss: 5.8707 - val_accuracy: 0.0897 - val_loss: 6.5003
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 43s 62ms/step - accuracy: 0.1037 - loss: 5.7000 - val_accuracy: 0.0939 - val_loss: 6.5108
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 62ms/step - accuracy: 0.1128 - loss: 5.5436 - val_accuracy: 0.0990 - val_loss: 6.5216
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.1224 - loss: 5.3880 - val_accuracy: 0.1031 - val_loss: 6.5398
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.1315 - loss: 5.2365 - val_accuracy: 0.1061 - val_loss: 6.5760
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1398 - loss: 5.0940 - val_accuracy: 0.1060 - val_loss: 6.6184
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.1473 - loss: 4.9580 - val_accuracy: 0.1085 - val_loss: 6.6561
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.1545 - loss: 4.8249 - val_accuracy: 0.1102 - val_loss: 6.7012
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.1627 - loss: 4.6949 - val_accuracy: 0.1088 - val_loss: 6.7618
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.1706 - loss: 4.5690 - val_accuracy: 0.1114 - val_loss: 6.8218
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.1792 - loss: 4.4466 - val_accuracy: 0.1110 - val_loss: 6.8744
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.1907 - loss: 4.3258 - val_accuracy: 0.1103 - val_loss: 6.9354
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2028 - loss: 4.2111 - val_accuracy: 0.1112 - val_loss: 7.0141
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.2146 - loss: 4.0986 - val_accuracy: 0.1108 - val_loss: 7.0930
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2289 - loss: 3.9910 - val_accuracy: 0.1087 - val_loss: 7.1608
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2444 - loss: 3.8872 - val_accuracy: 0.1092 - val_loss: 7.2373
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.2565 - loss: 3.7892 - val_accuracy: 0.1102 - val_loss: 7.3091
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.2713 - loss: 3.6960 - val_accuracy: 0.1078 - val_loss: 7.3861
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.2841 - loss: 3.6089 - val_accuracy: 0.1068 - val_loss: 7.4695
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.2983 - loss: 3.5253 - val_accuracy: 0.1080 - val_loss: 7.5428
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.3085 - loss: 3.4478 - val_accuracy: 0.1080 - val_loss: 7.6198
Epoch 25/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.3208 - loss: 3.3744 - val_accuracy: 0.1053 - val_loss: 7.6884
Epoch 26/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.3336 - loss: 3.3038 - val_accuracy: 0.1061 - val_loss: 7.7602
Epoch 27/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.3446 - loss: 3.2370 - val_accuracy: 0.1074 - val_loss: 7.8531
Epoch 28/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.3542 - loss: 3.1731 - val_accuracy: 0.1071 - val_loss: 7.9130
Epoch 29/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.3642 - loss: 3.1116 - val_accuracy: 0.1042 - val_loss: 7.9870
Epoch 30/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.3745 - loss: 3.0532 - val_accuracy: 0.1055 - val_loss: 8.0523
Epoch 31/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.3828 - loss: 2.9964 - val_accuracy: 0.1038 - val_loss: 8.1299
Epoch 32/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.3924 - loss: 2.9409 - val_accuracy: 0.1046 - val_loss: 8.1980
Epoch 33/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.4006 - loss: 2.8880 - val_accuracy: 0.1036 - val_loss: 8.2587
Epoch 34/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.4103 - loss: 2.8395 - val_accuracy: 0.1034 - val_loss: 8.3329
Epoch 35/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.4173 - loss: 2.7891 - val_accuracy: 0.1008 - val_loss: 8.3936
Epoch 36/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.4264 - loss: 2.7405 - val_accuracy: 0.1013 - val_loss: 8.4641
Epoch 37/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.4345 - loss: 2.6939 - val_accuracy: 0.1027 - val_loss: 8.5180
Epoch 38/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.4432 - loss: 2.6494 - val_accuracy: 0.0992 - val_loss: 8.5853
Epoch 39/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.4518 - loss: 2.6067 - val_accuracy: 0.0996 - val_loss: 8.6451
Epoch 40/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 44s 61ms/step - accuracy: 0.4589 - loss: 2.5629 - val_accuracy: 0.0986 - val_loss: 8.7194
Epoch 41/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.4669 - loss: 2.5216 - val_accuracy: 0.0986 - val_loss: 8.7795
Epoch 42/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.4714 - loss: 2.4830 - val_accuracy: 0.0977 - val_loss: 8.8392
Epoch 43/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.4812 - loss: 2.4419 - val_accuracy: 0.0986 - val_loss: 8.8980
Epoch 44/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.4887 - loss: 2.4036 - val_accuracy: 0.0969 - val_loss: 8.9681
Epoch 45/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.4947 - loss: 2.3681 - val_accuracy: 0.0976 - val_loss: 9.0154
Epoch 46/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.5013 - loss: 2.3323 - val_accuracy: 0.0958 - val_loss: 9.0832
Epoch 47/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.5082 - loss: 2.2952 - val_accuracy: 0.0934 - val_loss: 9.1320
Epoch 48/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5175 - loss: 2.2619 - val_accuracy: 0.0947 - val_loss: 9.2093
Epoch 49/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.5215 - loss: 2.2283 - val_accuracy: 0.0939 - val_loss: 9.2530
Epoch 50/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.5287 - loss: 2.1949 - val_accuracy: 0.0929 - val_loss: 9.3091
Epoch 51/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 54ms/step - accuracy: 0.5333 - loss: 2.1627 - val_accuracy: 0.0934 - val_loss: 9.3693
Epoch 52/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5400 - loss: 2.1312 - val_accuracy: 0.0916 - val_loss: 9.4224
Epoch 53/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5467 - loss: 2.1010 - val_accuracy: 0.0924 - val_loss: 9.4899
Epoch 54/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.5512 - loss: 2.0711 - val_accuracy: 0.0915 - val_loss: 9.5477
Epoch 55/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5568 - loss: 2.0411 - val_accuracy: 0.0914 - val_loss: 9.6037
Epoch 56/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.5629 - loss: 2.0123 - val_accuracy: 0.0907 - val_loss: 9.6623
Epoch 57/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.5689 - loss: 1.9843 - val_accuracy: 0.0867 - val_loss: 9.7314
Epoch 58/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.5740 - loss: 1.9579 - val_accuracy: 0.0887 - val_loss: 9.7690
Epoch 59/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.5797 - loss: 1.9293 - val_accuracy: 0.0903 - val_loss: 9.8179
Epoch 60/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.5854 - loss: 1.9034 - val_accuracy: 0.0880 - val_loss: 9.8946
Epoch 61/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 59ms/step - accuracy: 0.5913 - loss: 1.8776 - val_accuracy: 0.0881 - val_loss: 9.9383
Epoch 62/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.5944 - loss: 1.8526 - val_accuracy: 0.0875 - val_loss: 9.9828
Epoch 63/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6013 - loss: 1.8286 - val_accuracy: 0.0882 - val_loss: 10.0360
Epoch 64/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6054 - loss: 1.8050 - val_accuracy: 0.0863 - val_loss: 10.0951
Epoch 65/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.6100 - loss: 1.7792 - val_accuracy: 0.0863 - val_loss: 10.1587
Epoch 66/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6153 - loss: 1.7572 - val_accuracy: 0.0875 - val_loss: 10.2195
Epoch 67/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6204 - loss: 1.7335 - val_accuracy: 0.0850 - val_loss: 10.2586
Epoch 68/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6250 - loss: 1.7116 - val_accuracy: 0.0868 - val_loss: 10.3055
Epoch 69/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6287 - loss: 1.6904 - val_accuracy: 0.0860 - val_loss: 10.3646
Epoch 70/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6341 - loss: 1.6684 - val_accuracy: 0.0834 - val_loss: 10.4099
Epoch 71/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6378 - loss: 1.6476 - val_accuracy: 0.0840 - val_loss: 10.4823
Epoch 72/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6418 - loss: 1.6255 - val_accuracy: 0.0839 - val_loss: 10.5312
Epoch 73/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 59ms/step - accuracy: 0.6480 - loss: 1.6063 - val_accuracy: 0.0830 - val_loss: 10.5655
Epoch 74/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.6508 - loss: 1.5855 - val_accuracy: 0.0831 - val_loss: 10.6248
Epoch 75/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6554 - loss: 1.5664 - val_accuracy: 0.0805 - val_loss: 10.6737
Epoch 76/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6601 - loss: 1.5462 - val_accuracy: 0.0821 - val_loss: 10.7209
Epoch 77/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6643 - loss: 1.5286 - val_accuracy: 0.0822 - val_loss: 10.7645
Epoch 78/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 60ms/step - accuracy: 0.6689 - loss: 1.5090 - val_accuracy: 0.0807 - val_loss: 10.8092
Epoch 79/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6721 - loss: 1.4901 - val_accuracy: 0.0824 - val_loss: 10.8712
Epoch 80/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6767 - loss: 1.4730 - val_accuracy: 0.0801 - val_loss: 10.9010
Epoch 81/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6792 - loss: 1.4557 - val_accuracy: 0.0805 - val_loss: 10.9776
Epoch 82/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.6831 - loss: 1.4386 - val_accuracy: 0.0804 - val_loss: 11.0280
Epoch 83/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6869 - loss: 1.4212 - val_accuracy: 0.0818 - val_loss: 11.0907
Epoch 84/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6901 - loss: 1.4036 - val_accuracy: 0.0800 - val_loss: 11.1161
Epoch 85/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.6934 - loss: 1.3894 - val_accuracy: 0.0812 - val_loss: 11.1749
Epoch 86/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.6973 - loss: 1.3715 - val_accuracy: 0.0793 - val_loss: 11.2261
Epoch 87/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.7001 - loss: 1.3581 - val_accuracy: 0.0806 - val_loss: 11.2624
Epoch 88/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.7047 - loss: 1.3396 - val_accuracy: 0.0798 - val_loss: 11.3122
Epoch 89/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.7077 - loss: 1.3246 - val_accuracy: 0.0783 - val_loss: 11.3543
Epoch 90/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.7117 - loss: 1.3088 - val_accuracy: 0.0769 - val_loss: 11.4060
Epoch 91/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.7140 - loss: 1.2956 - val_accuracy: 0.0793 - val_loss: 11.4631
Epoch 92/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 55ms/step - accuracy: 0.7170 - loss: 1.2803 - val_accuracy: 0.0787 - val_loss: 11.5149
Epoch 93/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.7210 - loss: 1.2663 - val_accuracy: 0.0783 - val_loss: 11.5470
Epoch 94/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.7249 - loss: 1.2518 - val_accuracy: 0.0763 - val_loss: 11.5978
Epoch 95/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.7266 - loss: 1.2380 - val_accuracy: 0.0787 - val_loss: 11.6382
Epoch 96/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.7293 - loss: 1.2245 - val_accuracy: 0.0766 - val_loss: 11.6886
Epoch 97/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.7334 - loss: 1.2113 - val_accuracy: 0.0770 - val_loss: 11.7325
Epoch 98/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7357 - loss: 1.1976 - val_accuracy: 0.0765 - val_loss: 11.7755
Epoch 99/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.7379 - loss: 1.1839 - val_accuracy: 0.0759 - val_loss: 11.8356
Epoch 100/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 55ms/step - accuracy: 0.7409 - loss: 1.1720 - val_accuracy: 0.0753 - val_loss: 11.8822

In [ ]:

lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
from tensorflow.keras.models import load_model
lstm_model = load_model('lstm_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
index_to_word = {}
for word, index in tokenizer.word_index.items():
    index_to_word[index] = word

In [ ]:
def predictor(model,tokenizer,text,max_len):
  text=text.lower()

  seq=tokenizer.texts_to_sequences([text])
  padded_seq=pad_sequences(seq,maxlen=max_len,padding='pre')
  pred=model.predict(padded_seq,verbose=0)
  pred_word_index=np.argmax(pred)
  return index_to_word[pred_word_index]

In [ ]:
seed_text="life is a"
next_word=predictor(lstm_model,tokenizer,seed_text,max_len)
print(seed_text,next_word)

life is a series

In [ ]:
def generate_quotes(model,tokenizer,seed_text,max_len,num_words):
  for _ in range(num_words):
    next_word=predictor(model,tokenizer,seed_text,max_len)
    if next_word is None:
      break
    seed_text += " "+ next_word
  return seed_text

In [ ]:
seed="are you a"
generate_text = generate_quotes(lstm_model,tokenizer,seed,max_len,10)
print(generate_text)

are you a person needs just because that is the man who can

In [ ]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

In [ ]:


with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)